// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Control: typeof import('./src/components/YuFlowChart/src/Control.vue')['default']
    DataDialog: typeof import('./src/components/YuFlowChart/src/DataDialog.vue')['default']
    EditorImage: typeof import('./src/components/YuTinymce/src/components/EditorImage.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Index2: typeof import('./src/components/YuPassword/src/index2.vue')['default']
    NodePanel: typeof import('./src/components/YuFlowChart/src/NodePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./src/components/YuBreadCrumb/src/index.vue')['default']
    Strength: typeof import('./src/components/YuPassword/src/strength.vue')['default']
    TextHoverEffect: typeof import('./src/components/TextHoverEffect/index.vue')['default']
  }
}

export {}
