// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextHoverEffect: typeof import('./TextHoverEffect/index.vue')['default']
    YuBreadCrumbSrc: typeof import('./YuBreadCrumb/src/index.vue')['default']
    YuCopyrightSrc: typeof import('./YuCopyright/src/index.vue')['default']
    YuCountToSrc: typeof import('./YuCountTo/src/index.vue')['default']
    YuFlowChartSrcControl: typeof import('./YuFlowChart/src/Control.vue')['default']
    YuFlowChartSrcDataDialog: typeof import('./YuFlowChart/src/DataDialog.vue')['default']
    YuFlowChartSrcNodePanel: typeof import('./YuFlowChart/src/NodePanel.vue')['default']
    YuHamBurgerSrc: typeof import('./YuHamBurger/src/index.vue')['default']
    YuLayoutSrc: typeof import('./YuLayout/src/index.vue')['default']
    YuPanelCardSrc: typeof import('./YuPanelCard/src/index.vue')['default']
    YuPasswordSrc: typeof import('./YuPassword/src/index.vue')['default']
    YuPasswordSrcIndex2: typeof import('./YuPassword/src/index2.vue')['default']
    YuPasswordSrcStrength: typeof import('./YuPassword/src/strength.vue')['default']
    YuScreenFullSrc: typeof import('./YuScreenFull/src/index.vue')['default']
    YuStreetMapSrc: typeof import('./YuStreetMap/src/index.vue')['default']
    YuSvgIconSrc: typeof import('./YuSvgIcon/src/index.vue')['default']
    YuThumbSrc: typeof import('./YuThumb/src/index.vue')['default']
    YuTinymceSrc: typeof import('./YuTinymce/src/index.vue')['default']
    YuTinymceSrcComponentsEditorImage: typeof import('./YuTinymce/src/components/EditorImage.vue')['default']
  }
}

export {}
